### PR TITLE
Aggregate loss by unique zones

### PR DESCRIPTION
**Pull request by ptormene**
See https://github.com/gem/oq-svir-qgis/pull/24

### CODE REVIEW

**Comment by mbernasocchi** [comment]
are your tests passing?

**Comment by ptormene** [comment]
I have errors too, but they seem to be caused by importing issues. I am investigating.

**Comment by ptormene** [comment]
Tests pass if I run `source scripts/run-env-linux.sh /usr; make test`

**Comment by mbernasocchi** [comment]
LGTM

**Pull request merged**
